// === AI-GENERATED (Generated by AI) ===
// Platform: Microsoft Copilot
// Model/LLM: GitHub Copilot
// Reviewed & adapted by: Team Member 4
// === END AI-GENERATED ===

pipeline {
    agent any

    triggers {
        githubPush()
    }

    options {
        timestamps()
        disableConcurrentBuilds()
        skipDefaultCheckout(true)
        buildDiscarder(logRotator(numToKeepStr: '20'))
    }

    environment {
        APP_IMAGE = 'devops-capstone-app'
        PROXY_IMAGE = 'devops-capstone-proxy'
        COLOR = 'green'
        REQUIRE_DOCKER = '1'
    }

    stages {
        stage('Checkout') {
            steps { checkout scm }
        }
        stage('Validate') {
            steps { sh './scripts/validate.sh' }
        }
        stage('Prepare Build') {
            steps {
                sh './scripts/prepare-build.sh'
                script { env.IMAGE_TAG = "${env.BUILD_NUMBER}-${sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()}" }
                sh 'printf "IMAGE_TAG=%s\n" "$IMAGE_TAG" >> .build/metadata.env'
            }
        }
        stage('Build Images') {
            steps { sh './scripts/build-image.sh' }
        }
        stage('Test Image') {
            steps { sh './scripts/test-image.sh' }
        }
        stage('Security Scan') {
            steps {
                sh "if git grep -n -I -E '(AWS_SECRET_ACCESS_KEY|BEGIN (RSA|OPENSSH) PRIVATE KEY)' -- ':!*.md'; then echo 'Potential secret found in source.'; exit 1; fi"
                sh "command -v trivy >/dev/null && trivy image --exit-code 1 --severity HIGH,CRITICAL \"${APP_IMAGE}:${IMAGE_TAG}\" || echo 'Trivy is not installed; image scan skipped.'"
            }
        }
        stage('Push to ECR') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'aws-ci-credentials', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    sh './scripts/push-ecr.sh'
                }
            }
        }
        stage('Render Task Definitions') {
            steps { sh './scripts/render-task-definitions.sh' }
        }
        stage('Deploy Green') {
            steps { sh './scripts/deploy-green.sh' }
        }
        stage('Health Check Green') {
            steps { sh './scripts/health-check.sh' }
        }
        stage('Switch Proxy') {
            steps { sh './scripts/switch-proxy.sh' }
        }
        stage('Smoke Test') {
            steps { sh './scripts/smoke-test.sh' }
        }
        stage('Scale Down Blue') {
            steps { sh './scripts/scale-down-blue.sh' }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '.build/**, evidence/**', allowEmptyArchive: true
            sh 'docker rm -f devops-capstone-test 2>/dev/null || true'
        }
    }
}
