data "aws_ssm_parameter" "al2023_ami" {
  name = "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
}

data "aws_subnet" "selected" {
  id = var.subnet_id
}

resource "aws_security_group" "jenkins" {
  name        = "bootcamp-project-team3-jenkins-sg"
  description = "Security group for Jenkins EC2 managed through AWS SSM"
  vpc_id      = data.aws_subnet.selected.vpc_id

  egress {
    description = "Allow outbound traffic"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name        = "bootcamp-project-team3-jenkins-sg"
    Environment = "dev"
    ManagedBy   = "Terraform"
  }
}

resource "aws_instance" "jenkins" {
  ami           = data.aws_ssm_parameter.al2023_ami.value
  instance_type = var.instance_type

  subnet_id              = var.subnet_id
  vpc_security_group_ids = [aws_security_group.jenkins.id]

  iam_instance_profile = "Bootcamp-Instance-Profile"

  associate_public_ip_address = true

  root_block_device {
    volume_size = 20
    volume_type = "gp3"
    encrypted   = true
  }

  tags = {
    Name        = "bootcamp-project-team3-jenkins"
    Environment = "dev"
    ManagedBy   = "Terraform"
  }
}

resource "aws_s3_bucket" "team3" {
  bucket = var.bucket_name

  tags = {
    Name        = "bootcamp-project-team3-s3"
    Environment = "dev"
    ManagedBy   = "Terraform"
  }
}

resource "aws_s3_bucket_public_access_block" "team3" {
  bucket = aws_s3_bucket.team3.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "team3" {
  bucket = aws_s3_bucket.team3.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# Generated by AI: This code was generated with OpenAI ChatGPT using the GPT-5.6 Luna language model.

# ECR ===================================================================


resource "aws_ecr_repository" "app" {
  name                 = var.ecr_repository_name
  image_tag_mutability = "MUTABLE"

  image_scanning_configuration {
    scan_on_push = true
  }

  tags = {
    Name        = var.ecr_repository_name
    Environment = "dev"
    ManagedBy   = "Terraform"
    Project     = "bootcamp-automation"
  }
}


# ECS CLUSTER=====================================================


resource "aws_ecs_cluster" "app" {
  name = var.ecs_cluster_name

  setting {
    name  = "containerInsights"
    value = "enabled"
  }

  tags = {
    Name        = var.ecs_cluster_name
    Environment = "dev"
    ManagedBy   = "Terraform"
    Project     = "bootcamp-automation"
  }
}



# ECS TASK DEFINITION ======================================================


resource "aws_ecs_task_definition" "app" {
  family                   = var.ecs_task_family
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]

  cpu    = var.fargate_cpu
  memory = var.fargate_memory

  # Use the EXISTING IAM ROLE
  execution_role_arn = var.ecs_task_execution_role_arn

  container_definitions = jsonencode([
    {
      name      = var.container_name
      image     = "${aws_ecr_repository.app.repository_url}:latest"
      essential = true

      portMappings = [
        {
          containerPort = var.container_port
          protocol      = "tcp"
        }
      ]
    }
  ])

  tags = {
    Name        = var.ecs_task_family
    Environment = "dev"
    ManagedBy   = "Terraform"
    Project     = "bootcamp-automation"
  }
}



# ECS create FARGATE SERVICE ===============================================


resource "aws_ecs_service" "app" {
  name            = var.ecs_service_name
  cluster         = aws_ecs_cluster.app.id
  task_definition = aws_ecs_task_definition.app.arn

  desired_count = var.ecs_desired_count

  launch_type      = "FARGATE"
  platform_version = "LATEST"

  deployment_controller {
    type = "ECS"
  }

  network_configuration {
    subnets = var.subnet_ids

    security_groups = [
      var.security_group_id
    ]

    assign_public_ip = true
  }

  tags = {
    Name        = var.ecs_service_name
    Environment = "dev"
    ManagedBy   = "Terraform"
    Project     = "bootcamp-automation"
  }
}

