data "aws_ssm_parameter" "al2023_ami" {
  name = "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
}

data "aws_subnet" "selected" {
  id = var.subnet_id
}

resource "aws_security_group" "jenkins" {
  name        = "bootcamp-project-team3-jenkins-sg"
  description = "Security group for Jenkins EC2 managed through AWS SSM"
  vpc_id      = data.aws_subnet.selected.vpc_id

  egress {
    description = "Allow outbound traffic"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name        = "bootcamp-project-team3-jenkins-sg"
    Environment = "dev"
    ManagedBy   = "Terraform"
  }
}

resource "aws_instance" "jenkins" {
  ami           = data.aws_ssm_parameter.al2023_ami.value
  instance_type = var.instance_type

  subnet_id              = var.subnet_id
  vpc_security_group_ids = [aws_security_group.jenkins.id]

  iam_instance_profile = "Bootcamp-Instance-Profile"

  associate_public_ip_address = true

  root_block_device {
    volume_size = 20
    volume_type = "gp3"
    encrypted   = true
  }

  tags = {
    Name        = "bootcamp-project-team3-jenkins"
    Environment = "dev"
    ManagedBy   = "Terraform"
  }
}

resource "aws_s3_bucket" "team3" {
  bucket = var.bucket_name

  tags = {
    Name        = "bootcamp-project-team3-s3"
    Environment = "dev"
    ManagedBy   = "Terraform"
  }
}

resource "aws_s3_bucket_public_access_block" "team3" {
  bucket = aws_s3_bucket.team3.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "team3" {
  bucket = aws_s3_bucket.team3.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# Generated by AI: This code was generated with OpenAI ChatGPT using the GPT-5.6 Luna language model.
