variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "eu-west-1"
}

variable "subnet_id" {
  description = "Existing subnet ID for the Jenkins EC2"
  type        = string
}

variable "instance_type" {
  description = "Jenkins EC2 instance type"
  type        = string
  default     = "t3.medium"
}

variable "bucket_name" {
  description = "Globally unique S3 bucket name"
  type        = string
}

# Generated by AI: This code was generated with OpenAI ChatGPT using the GPT-5.6 Luna language model.

# =========================
# ECR
# =========================

variable "ecr_repository_name" {
  description = "ECR repository name"
  type        = string
  default     = "devops-app"
}

# =========================
# ECS
# =========================

variable "ecs_cluster_name" {
  description = "ECS cluster name"
  type        = string
  default     = "devops-ecs-cluster"
}


variable "ecs_task_execution_role_arn" {
  description = "ECS task execution role"
  type        = string
  default     = "devops-app-service"
}


variable "ecs_service_name" {
  description = "ECS service name"
  type        = string
  default     = "devops-app-service"
}

variable "ecs_task_family" {
  description = "ECS task definition family"
  type        = string
  default     = "devops-app"
}

variable "container_name" {
  description = "Container name"
  type        = string
  default     = "devops-app"
}

variable "container_port" {
  description = "Application container port"
  type        = number
  default     = 80
}

variable "fargate_cpu" {
  description = "Fargate CPU units"
  type        = number
  default     = 256
}

variable "fargate_memory" {
  description = "Fargate memory in MiB"
  type        = number
  default     = 512
}

variable "ecs_desired_count" {
  description = "Desired number of ECS tasks"
  type        = number
  default     = 2
}

variable "subnet_ids" {
  description = "Subnets for ECS Fargate"
  type        = list(string)
}