variable "aws_region" {
  description = "AWS region"
  type        = string
  default     = "eu-west-1"
}

variable "subnet_id" {
  description = "Existing subnet ID for the Jenkins EC2"
  type        = string
}

variable "instance_type" {
  description = "Jenkins EC2 instance type"
  type        = string
  default     = "t3.medium"
}

variable "bucket_name" {
  description = "Globally unique S3 bucket name"
  type        = string
}

# Generated by AI: This code was generated with OpenAI ChatGPT using the GPT-5.6 Luna language model.