#!/bin/bash

sudo dnf update -y

sudo dnf install -y python3 python3-pip git

python3 -m pip install --user ansible

ansible --version

# Generated by AI: This code was generated with OpenAI ChatGPT using the GPT-5.6 Luna language model.