#!/usr/bin/env bash
# === AI-GENERATED (Generated by AI) ===
# Platform: Microsoft Copilot
# Model/LLM: GitHub Copilot
# Reviewed & adapted by: Team Member 4
# === END AI-GENERATED ===
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
: "${IMAGE_TAG:?IMAGE_TAG must be set}"
docker build -f "$ROOT_DIR/.build/docker/Dockerfile" -t "${APP_IMAGE:-devops-capstone-app}:$IMAGE_TAG" "$ROOT_DIR/.build"
if [[ -f "$ROOT_DIR/proxy/Dockerfile" ]]; then
    docker build -f "$ROOT_DIR/proxy/Dockerfile" -t "${PROXY_IMAGE:-devops-capstone-proxy}:$IMAGE_TAG" "$ROOT_DIR"
else
    echo 'Proxy image files are not present; app image built, proxy build deferred.'
fi
