#!/usr/bin/env bash
# === AI-GENERATED (Generated by AI) ===
# Platform: Microsoft Copilot
# Model/LLM: GitHub Copilot
# Reviewed & adapted by: Team Member 4
# === END AI-GENERATED ===
set -euo pipefail

: "${AWS_DEFAULT_REGION:=eu-west-1}"
: "${ECS_CLUSTER_NAME:?ECS_CLUSTER_NAME must be set}"
: "${ECS_SERVICE_GREEN:?ECS_SERVICE_GREEN must be set}"
: "${ECS_TASK_FAMILY_APP:?ECS_TASK_FAMILY_APP must be set}"
: "${ECR_REPOSITORY_APP:?ECR_REPOSITORY_APP must be set}"
: "${IMAGE_TAG:?IMAGE_TAG must be set}"
TASK_DEF="${TASK_DEFINITION_FILE:-.build/task-definition-green.json}"
if [[ ! -f "$TASK_DEF" ]]; then
    echo "Missing $TASK_DEF. Provide a rendered ECS task definition from Terraform/TM2." >&2
    exit 1
fi
NEW_TASK_DEF=$(aws ecs register-task-definition --region "$AWS_DEFAULT_REGION" --family "$ECS_TASK_FAMILY_APP" --cli-input-json "file://$TASK_DEF" --query 'taskDefinition.taskDefinitionArn' --output text)
aws ecs update-service --region "$AWS_DEFAULT_REGION" --cluster "$ECS_CLUSTER_NAME" --service "$ECS_SERVICE_GREEN" --task-definition "$NEW_TASK_DEF" >/dev/null
aws ecs wait services-stable --region "$AWS_DEFAULT_REGION" --cluster "$ECS_CLUSTER_NAME" --services "$ECS_SERVICE_GREEN"
printf '%s\n' "GREEN_TASK_DEFINITION=$NEW_TASK_DEF" > evidence/green-deployment.env
