#!/usr/bin/env bash
# === AI-GENERATED (Generated by AI) ===
# Platform: Microsoft Copilot
# Model/LLM: GitHub Copilot
# Reviewed & adapted by: Team Member 4
# === END AI-GENERATED ===
set -euo pipefail

: "${GREEN_HEALTH_URL:?GREEN_HEALTH_URL must directly address the green service}"
ATTEMPTS="${HEALTH_ATTEMPTS:-30}"
for attempt in $(seq 1 "$ATTEMPTS"); do
    if curl --fail --silent --show-error --max-time 5 "$GREEN_HEALTH_URL" | grep -qx 'OK'; then
        echo 'GREEN health check passed.'
        exit 0
    fi
    sleep 5
done
echo 'GREEN health check failed; proxy switch will not run.' >&2
exit 1
