#!/usr/bin/env bash
# === AI-GENERATED (Generated by AI) ===
# Platform: Microsoft Copilot
# Model/LLM: GitHub Copilot
# Reviewed & adapted by: Team Member 4
# === END AI-GENERATED ===
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="${ROOT_DIR}/.build"
BUILD_NUMBER="${BUILD_NUMBER:-local}"
GIT_COMMIT="${GIT_COMMIT:-$(git -C "$ROOT_DIR" rev-parse --short HEAD)}"
COLOR="${COLOR:-green}"
VERSION="${VERSION:-${BUILD_NUMBER}-${GIT_COMMIT}}"
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR/app" "$BUILD_DIR/docker"
cp "$ROOT_DIR/app/index.html" "$ROOT_DIR/app/health.html" "$ROOT_DIR/app/version.json" "$BUILD_DIR/app/"
cp "$ROOT_DIR/docker/Dockerfile" "$ROOT_DIR/docker/nginx-app.conf" "$BUILD_DIR/docker/"
find "$BUILD_DIR/app" -type f -exec sed -i \
    -e "s|__VERSION__|${VERSION}|g" \
    -e "s|__GIT_COMMIT__|${GIT_COMMIT}|g" \
    -e "s|__BUILD_NUMBER__|${BUILD_NUMBER}|g" \
    -e "s|__COLOR__|${COLOR}|g" {} +
printf '%s\n' "VERSION=$VERSION" "GIT_COMMIT=$GIT_COMMIT" "BUILD_NUMBER=$BUILD_NUMBER" "COLOR=$COLOR" > "$BUILD_DIR/metadata.env"
echo "Prepared $BUILD_DIR for $VERSION."
