#!/usr/bin/env bash
# === AI-GENERATED (Generated by AI) ===
# Platform: Microsoft Copilot
# Model/LLM: GitHub Copilot
# Reviewed & adapted by: Team Member 4
# === END AI-GENERATED ===
set -euo pipefail

: "${AWS_DEFAULT_REGION:=eu-west-1}"
: "${ECR_REPOSITORY_APP:?ECR_REPOSITORY_APP must be an ECR repository URI}"
: "${IMAGE_TAG:?IMAGE_TAG must be set}"
APP_LOCAL="${APP_IMAGE:-devops-capstone-app}:$IMAGE_TAG"
APP_REMOTE="$ECR_REPOSITORY_APP:$IMAGE_TAG"
REGISTRY="${ECR_REPOSITORY_APP%%/*}"
aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$REGISTRY"
docker tag "$APP_LOCAL" "$APP_REMOTE"
docker push "$APP_REMOTE"
if docker image inspect "${PROXY_IMAGE:-devops-capstone-proxy}:$IMAGE_TAG" >/dev/null 2>&1; then
    : "${ECR_REPOSITORY_PROXY:?ECR_REPOSITORY_PROXY must be set when a proxy image exists}"
    PROXY_REMOTE="$ECR_REPOSITORY_PROXY:$IMAGE_TAG"
    docker tag "${PROXY_IMAGE:-devops-capstone-proxy}:$IMAGE_TAG" "$PROXY_REMOTE"
    docker push "$PROXY_REMOTE"
fi
mkdir -p evidence
printf '%s\n' "APP_IMAGE=$APP_REMOTE" "PROXY_IMAGE=${ECR_REPOSITORY_PROXY:-not-built}" > evidence/images.env
