#!/usr/bin/env bash

set -euo pipefail

# === AI-GENERATED (Generated by AI) ===

# Platform: Microsoft Copilot

# Model/LLM: GPT-5 reasoning model

# Reviewed & adapted by: Alexey Glushchenko

# === END AI-GENERATED ===

AWS_REGION="${AWS_REGION:-eu-west-1}"

AWS_ACCOUNT_ID="${AWS_ACCOUNT_ID:-597765856364}"

ECR_REPOSITORY="${ECR_REPOSITORY:-bootcamp-app-team3}"

ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"

ECR_REPOSITORY_URI="${ECR_REGISTRY}/${ECR_REPOSITORY}"

: "${BUILD_TAG:?BUILD_TAG is required}"

: "${APP_IMAGE:?APP_IMAGE is required}"

echo "Verifying AWS identity..."

aws sts get-caller-identity --region "${AWS_REGION}"

echo "Verifying ECR repository ${ECR_REPOSITORY}..."

aws ecr describe-repositories --repository-names "${ECR_REPOSITORY}" --region "${AWS_REGION}" >/dev/null

echo "Authenticating Docker to ${ECR_REGISTRY}..."

aws ecr get-login-password --region "${AWS_REGION}" | docker login --username AWS --password-stdin "${ECR_REGISTRY}"

VERSIONED_IMAGE="${ECR_REPOSITORY_URI}:${BUILD_TAG}"

LATEST_IMAGE="${ECR_REPOSITORY_URI}:latest"

if [[ "${APP_IMAGE}" != "${VERSIONED_IMAGE}" ]]; then
  echo "Tagging ${APP_IMAGE} as ${VERSIONED_IMAGE}..."
  docker tag "${APP_IMAGE}" "${VERSIONED_IMAGE}"
fi

echo "Tagging ${APP_IMAGE} as ${LATEST_IMAGE} for the current ECS task definition..."

docker tag "${APP_IMAGE}" "${LATEST_IMAGE}"

echo "Pushing immutable build tag ${BUILD_TAG}..."

docker push "${VERSIONED_IMAGE}"

echo "Pushing compatibility tag latest..."

docker push "${LATEST_IMAGE}"

echo "Verifying uploaded build tag..."

aws ecr describe-images --repository-name "${ECR_REPOSITORY}" --image-ids imageTag="${BUILD_TAG}" --region "${AWS_REGION}" --query "imageDetails[0].{Tags:imageTags,Digest:imageDigest,Pushed:imagePushedAt}" --output json

echo "ECR push completed."

echo "Versioned image: ${VERSIONED_IMAGE}"

echo "Compatibility image: ${LATEST_IMAGE}"