#!/usr/bin/env bash
# === AI-GENERATED (Generated by AI) ===
# Platform: Microsoft Copilot
# Model/LLM: GitHub Copilot
# Reviewed & adapted by: Team Member 4
# === END AI-GENERATED ===
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
: "${ECR_REPOSITORY_APP:?ECR_REPOSITORY_APP must be set}"
: "${IMAGE_TAG:?IMAGE_TAG must be set}"
: "${EXECUTION_ROLE_ARN:?EXECUTION_ROLE_ARN must be set}"
: "${TASK_ROLE_ARN:?TASK_ROLE_ARN must be set}"
: "${LOG_GROUP_APP:?LOG_GROUP_APP must be set}"
: "${APP_UPSTREAM:?APP_UPSTREAM must be set}"
: "${ECR_REPOSITORY_PROXY:?ECR_REPOSITORY_PROXY must be set}"
: "${LOG_GROUP_PROXY:?LOG_GROUP_PROXY must be set}"
: "${ECS_TASK_FAMILY_APP:?ECS_TASK_FAMILY_APP must be set}"
: "${ECS_TASK_FAMILY_PROXY:?ECS_TASK_FAMILY_PROXY must be set}"
mkdir -p "$ROOT_DIR/.build"
export APP_IMAGE_URI="$ECR_REPOSITORY_APP:$IMAGE_TAG"
export PROXY_IMAGE_URI="$ECR_REPOSITORY_PROXY:$IMAGE_TAG"
export AWS_REGION="${AWS_DEFAULT_REGION:-eu-west-1}"
envsubst < "$ROOT_DIR/deploy/task-definition-app.json.template" > "$ROOT_DIR/.build/task-definition-green.json"
envsubst < "$ROOT_DIR/deploy/task-definition-proxy.json.template" > "$ROOT_DIR/.build/task-definition-proxy-green.json"
jq empty "$ROOT_DIR/.build/task-definition-green.json"
jq empty "$ROOT_DIR/.build/task-definition-proxy-green.json"
echo 'Rendered valid ECS task definitions.'
