#!/usr/bin/env bash
# === AI-GENERATED (Generated by AI) ===
# Platform: Microsoft Copilot
# Model/LLM: GitHub Copilot
# Reviewed & adapted by: Team Member 4
# === END AI-GENERATED ===
set -euo pipefail

: "${AWS_DEFAULT_REGION:=eu-west-1}"
: "${ECS_CLUSTER_NAME:?ECS_CLUSTER_NAME must be set}"
: "${ECS_SERVICE_BLUE:?ECS_SERVICE_BLUE must be set}"
BLUE_DESIRED_COUNT="${BLUE_DESIRED_COUNT:-0}"
aws ecs update-service --region "$AWS_DEFAULT_REGION" --cluster "$ECS_CLUSTER_NAME" --service "$ECS_SERVICE_BLUE" --desired-count "$BLUE_DESIRED_COUNT" >/dev/null
echo "BLUE desired count set to $BLUE_DESIRED_COUNT after GREEN became active."
