#!/usr/bin/env bash
# === AI-GENERATED (Generated by AI) ===
# Platform: Microsoft Copilot
# Model/LLM: GitHub Copilot
# Reviewed & adapted by: Team Member 4
# === END AI-GENERATED ===
set -euo pipefail

: "${ALB_URL:?ALB_URL must be set}"
curl --fail --silent --show-error "$ALB_URL/" >/dev/null
curl --fail --silent --show-error "$ALB_URL/health.html" | grep -qx 'OK'
VERSION_JSON="$(curl --fail --silent --show-error "$ALB_URL/version.json")"
printf '%s\n' "$VERSION_JSON" | grep -q '"color"[[:space:]]*:[[:space:]]*"green"'
mkdir -p evidence
printf '%s\n' "$VERSION_JSON" > evidence/public-version.json
echo 'Public ALB smoke test passed.'
