#!/usr/bin/env bash
# === AI-GENERATED (Generated by AI) ===
# Platform: Microsoft Copilot
# Model/LLM: GitHub Copilot
# Reviewed & adapted by: Team Member 4
# === END AI-GENERATED ===
set -euo pipefail

: "${AWS_DEFAULT_REGION:=eu-west-1}"
: "${ECS_CLUSTER_NAME:?ECS_CLUSTER_NAME must be set}"
: "${ECS_SERVICE_PROXY:?ECS_SERVICE_PROXY must be set}"
: "${PROXY_TASK_DEFINITION_FILE:?PROXY_TASK_DEFINITION_FILE must render the GREEN upstream}"
if [[ ! -f "$PROXY_TASK_DEFINITION_FILE" ]]; then
    echo "Missing proxy task definition: $PROXY_TASK_DEFINITION_FILE" >&2
    exit 1
fi
PROXY_TASK_DEF=$(aws ecs register-task-definition --region "$AWS_DEFAULT_REGION" --family "${ECS_TASK_FAMILY_PROXY:?ECS_TASK_FAMILY_PROXY must be set}" --cli-input-json "file://$PROXY_TASK_DEFINITION_FILE" --query 'taskDefinition.taskDefinitionArn' --output text)
aws ecs update-service --region "$AWS_DEFAULT_REGION" --cluster "$ECS_CLUSTER_NAME" --service "$ECS_SERVICE_PROXY" --task-definition "$PROXY_TASK_DEF" >/dev/null
aws ecs wait services-stable --region "$AWS_DEFAULT_REGION" --cluster "$ECS_CLUSTER_NAME" --services "$ECS_SERVICE_PROXY"
printf '%s\n' "PROXY_TASK_DEFINITION=$PROXY_TASK_DEF" "ACTIVE_COLOR=green" > evidence/proxy-switch.env
