#!/usr/bin/env bash
# === AI-GENERATED (Generated by AI) ===
# Platform: Microsoft Copilot
# Model/LLM: GitHub Copilot
# Reviewed & adapted by: Team Member 4
# === END AI-GENERATED ===
set -euo pipefail

: "${IMAGE_TAG:?IMAGE_TAG must be set}"
IMAGE="${APP_IMAGE:-devops-capstone-app}:$IMAGE_TAG"
cleanup() { docker rm -f devops-capstone-test >/dev/null 2>&1 || true; }
trap cleanup EXIT
docker run -d --name devops-capstone-test -p 18080:8080 "$IMAGE" >/dev/null
for attempt in {1..20}; do
    curl -fsS http://127.0.0.1:18080/health.html >/dev/null && break
    sleep 2
done
curl -fsS http://127.0.0.1:18080/health.html | grep -qx 'OK'
curl -fsS http://127.0.0.1:18080/version.json | grep -q '"buildNumber"'
echo 'Container health and version checks passed.'
