#!/usr/bin/env bash
# === AI-GENERATED (Generated by AI) ===
# Platform: Microsoft Copilot
# Model/LLM: GitHub Copilot
# Reviewed & adapted by: Team Member 4
# === END AI-GENERATED ===
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
required=(app/index.html app/health.html app/version.json docker/Dockerfile docker/nginx-app.conf)
for path in "${required[@]}"; do
    test -f "$ROOT_DIR/$path" || { echo "Missing required file: $path" >&2; exit 1; }
done
if [[ "${REQUIRE_DOCKER:-0}" == '1' ]]; then
    command -v docker >/dev/null || { echo 'Docker is required for Jenkins builds.' >&2; exit 1; }
else
    echo 'Docker check skipped for local static validation.'
fi
command -v git >/dev/null || { echo 'Git is required.' >&2; exit 1; }
if git -C "$ROOT_DIR" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    git -C "$ROOT_DIR" diff --check
else
    echo 'Git diff check skipped because this shell cannot access the repository metadata.'
fi
echo 'Validation passed.'
